### ISSUE TITLE
Post "http://seed.nkn.org:30003": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Nyx2020** [nknorg/nkn-sdk-go#84]
i got a error like "Post "http://seed.nkn.org:30003": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",if all clients got this error,the transfer will stop ,and can't transfrer any data,unless restart
![nkn错误](https://user-images.githubusercontent.com/51039208/150903296-5269c4a8-44a7-443f-bfd5-f1af42062295.png)

so i wanna honw howto fix this problem and how to keep transfer statble as long as long time?
thanks for your reply

**Comment by yilunzhang** [comment]
This is caused by network timeout between your client and official seed node (hosted on Digital Ocean). Recently the load on our seed node is pretty stable, so it's probably because your client side has unstable connection to DO. We also saw that happened in some regions (e.g. China).

As far as I know, there is no single cloud provider that has good connections to all regions worldwide. For example, major cloud providers like AWS/GCP don't work well in China, while nodes that have good connection inside China don't work well outside China. We have tried using load balancer (e.g. CloudFlare) to point users in China to node in China, but it's not working all the time because some users even failed at the DNS resolution step in load balancer.

If you know your users main region, the most stable way is to use a seed node in that region when creating client or wallet. It can be one of the official seed node in that region, or your own node. If not, one way is probably letting user configure region or seed node themselves. I'm sure there are other ways and I'm happy to discuss about them.

**Comment by Nyx2020** [comment]
> This is caused by network timeout between your client and official seed node (hosted on Digital Ocean). Recently the load on our seed node is pretty stable, so it's probably because your client side has unstable connection to DO. We also saw that happened in some regions (e.g. China).
> 
> As far as I know, there is no single cloud provider that has good connections to all regions worldwide. For example, major cloud providers like AWS/GCP don't work well in China, while nodes that have good connection inside China don't work well outside China. We have tried using load balancer (e.g. CloudFlare) to point users in China to node in China, but it's not working all the time because some users even failed at the DNS resolution step in load balancer.
> 
> If you know your users main region, the most stable way is to use a seed node in that region when creating client or wallet. It can be one of the official seed node in that region, or your own node. If not, one way is probably letting user configure region or seed node themselves. I'm sure there are other ways and I'm happy to discuss about them.


so tank you,  where can i find the seed node of my region,and how can i build a sub seed node to connect to your official seed node

**Comment by yilunzhang** [comment]
There are current 8 official seed node, from `http://mainnet-seed-0001.nkn.org:30003` to `http://mainnet-seed-0008.nkn.org:30003`, each in a different region. `http://seed.nkn.org:30003` is just a load balancer pointing to one of those 8 nodes. You can try and see which one or ones are fastest from your region, and pass one or more to seed node (list) when creating client or wallet.

Official seed node is just a normal NKN full node. Any node in the network can be a seed node. A good place to start with is https://github.com/nknorg/nkn

**Comment by Nyx2020** [comment]
> There are current 8 official seed node, from `http://mainnet-seed-0001.nkn.org:30003` to `http://mainnet-seed-0008.nkn.org:30003`, each in a different region. `http://seed.nkn.org:30003` is just a load balancer pointing to one of those 8 nodes. You can try and see which one or ones are fastest from your region, and pass one or more to seed node (list) when creating client or wallet.
> 
> Official seed node is just a normal NKN full node. Any node in the network can be a seed node. A good place to start with is https://github.com/nknorg/nkn

OK，thank you
