### ISSUE TITLE
ConnectRetries cannot set 0, will be replaced by default 3

### ISSUE THREAD

**Issue by SteveCruise** [nknorg/nkn-sdk-go#94]
```go
// MergeClientConfig merges a given client config with the default client config
// recursively. Any non zero value fields will override the default config.
func MergeClientConfig(conf *ClientConfig) (*ClientConfig, error) {
	merged := GetDefaultClientConfig()
	if conf != nil {
		err := mergo.Merge(merged, conf, mergo.WithOverride)
		if err != nil {
			return nil, err
		}
	}
	return merged, nil
}
```
In ClientConfig's defination, 0 means unlimited retries.
```golang
// ClientConfig is the client configuration.
type ClientConfig struct {
	...
	ConnectRetries          int32          // Connnect to node retries (including the initial connect). 0 means unlimited retries.
	...
}
```

**Comment by yilunzhang** [comment]
This is expected if we want:
1. `ConnectRetries` field in `ClientConfig` structure is optional;
2. The default config has limited retries.
Because 0 is the null value in Go, one cannot distinguish between if a field is missing, or user explicitly pass 0. Maybe we can change the behavior to -1 means unlimited retries. Before that, a workaround would be using a large integer for practically unlimited retries.
